---
- name: Update servers
  hosts: servers
  remote_user: ec2-user
  become: yes
  become_method: sudo

  roles:
    - update

- name: Install docker
  hosts: jenkins
  remote_user: ec2-user
  become: yes
  become_method: sudo

  roles:
    - docker  

- name: Launch jenkins and Nginx
  hosts: jenkins
  remote_user: ec2-user
  become: yes
  become_method: sudo

  roles:
    - jenkins  
    - nginx